#ifndef _SETUPPARAMTABLE_H_
#define _SETUPPARAMTABLE_H_

#define BASICTEMPLATEFIELDNUMBER         24
#define MAX_NUMBER_ADD_TO_TEMPLATE_FIELD 10
typedef enum 
{
	MARKET_NONE	= 0,
    MARKET_ARGENTINA,
	MARKET_AUSTRALIA,
	MARKET_CANADA,
    MARKET_EUROPEAN_OIML,//OIML
	MARKET_USA_NTEP,		//NTEP
}SETUP_APPROVAL;

typedef enum
{
	ONE_RANGE = 0,
	//TWO_INTERVALS, 取消多分度
	TWO_RANGES,
}SETUP_RANGE;

typedef enum
{
	INCREAMENT_0POINT0001 = 0,
	INCREAMENT_0POINT0002,
	INCREAMENT_0POINT0005,
	INCREAMENT_0POINT001,
	INCREAMENT_0POINT002,
	INCREAMENT_0POINT005,
	INCREAMENT_0POINT01,
	INCREAMENT_0POINT02,
	INCREAMENT_0POINT05,
	INCREAMENT_0POINT1,
	INCREAMENT_0POINT2,
	INCREAMENT_0POINT5,
	INCREAMENT_1,
	INCREAMENT_2,
	INCREAMENT_5,
	INCREAMENT_10,
	INCREAMENT_20,
	INCREAMENT_50,
	INCREAMENT_100,
	INCREAMENT_200
}SETUP_INCREAMENT;

typedef enum
{
	AZM_DISABLE = 0,
	AZM_GROSS_ONLY,
	AZM_GROSS_NET
}SETUP_AZMMODE;

typedef enum
{
	AZM_0POINT5_DIVISION = 0,
	AZM_1_DIVISION,
	AZM_3_DIVISION,
	AZM_10_DIVISION
}SETUP_AZMDIVISION;

typedef enum
{
	POWERUP_ZERO_DISABLE = 0,
	POWERUP_ZERO_RANGE_4PERCENT,
	POWERUP_ZERO_RANGE_20PERCENT
}SETUP_ZERORANGE_POWERUP;

typedef enum
{
	PUSHBUTTON_ZERO_DISABLE = 0,
	PUSHBUTTON_ZERO_RANGE_4PERCENT,
	PUSHBUTTON_ZERO_RANGE_40PERCENT
}SETUP_ZERORANGE_PUSHBUTTON;

typedef enum
{
	UNDERZEROBLANKING_DISABLE = 0,
	UNDERZEROBLANKING_20D,
	UNDERZEROBLANKING_20DWITHZERO
}SETUP_UNDERZEROBLANKING;

typedef enum
{
	MOTION_DISABLE = 0,
	MOTION_RANGE_1DIVISION,
	MOTION_RANGE_3DIVISION
}SETUP_MOTIONRANGE;

typedef enum
{
	NOMOTION_INTERVAL_0POINT3_SECOND = 0,
	NOMOTION_INTERVAL_0POINT5_SECOND,
	NOMOTION_INTERVAL_0POINT7_SECOND,
	NOMOTION_INTERVAL_1_SECOND
}SETUP_NOMOTIONINTERVAL;

typedef enum
{
	NOMOTION_TIMEOUT_DISABLE = 0,
	NOMOTION_TIMEOUT_3_SECOND,
	NOMOTION_TIMEOUT_10_SECOND,
	NOMOTION_TIMEOUT_30_SECOND
}SETUP_MOTIONTIMEOUT;

typedef enum
{
	AUTOPRINT_RESETON_DEVIATION = 0,
	AUTOPRINT_RESETON_RETURN
}SETUP_AUTOPRINT_RESETMODE;

typedef enum
{
	COMASSIGNMENT_NONE = 0,
    COMASSIGNMENT_KINGBIRDCONTINUOUSOUTPUT,
    COMASSIGNMENT_8142CONTINUOUSOUTPUT,    
	COMASSIGNMENT_CONTINUOUSOUTPUT,
	COMASSIGNMENT_EXTENDEDCONTINUOUSOUTPUT,
	COMASSIGNMENT_DEMANDOUTPUT,
	COMASSIGNMENT_PRINTCLIENT,
    COMASSIGNMENT_REPORTS,
	COMASSIGNMENT_SICS,
	COMASSIGNMENT_VARIABLEACCESS, 
	COMASSIGNMENT_SCANBAR,
	COMASSIGNMENT_MULTI1,
	COMASSIGNMENT_MULTI2,
	COMASSIGNMENT_LABELPRINT,
}SETUP_COMASSIGNMENT;

typedef enum
{
	COMBAUDRATE_300 = 0,
	COMBAUDRATE_600,
	COMBAUDRATE_1200,
	COMBAUDRATE_2400,
	COMBAUDRATE_4800,
	COMBAUDRATE_9600,
	COMBAUDRATE_19200,
	COMBAUDRATE_38400,
	COMBAUDRATE_57600,
	COMBAUDRATE_115200
}SETUP_COMBAUDRATE;

typedef enum
{
	SYSTEMLINE_NONE = 0,
	SYSTEMLINE_DIO,
	SYSTEMLINE_TIME,
	SYSTEMLINE_BOTH
}SYSTEMLINE;

typedef enum
{
    PRINTTEMPLATE_BASIC_1 = 0,
    PRINTTEMPLATE_BASIC_2,
    PRINTTEMPLATE_BASIC_3,
    PRINTTEMPLATE_BASIC_A,
    PRINTTEMPLATE_BASIC_B,
    PRINTTEMPLATE_OVER_UNDER_6 = 5,
    PRINTTEMPLATE_PEAK_WEIGHT_7,
    PRINTTEMPLATE_ANIMAL_WEIGHING_8,
    PRINTTEMPLATE_COUNTING_9,
 	LABELPRINTTEMPLATE_1 = 9,
    LABELPRINTTEMPLATE_2,
    LPUSERTEMPLATE_11,
    LPUSERTEMPLATE_12,
    LPUSERTEMPLATE_13,
    LABELPRINTTEMPLATE_3,
    LABELPRINTTEMPLATE_4,
    LPUSERTEMPLATE_21,
    LPUSERTEMPLATE_22,
    LPUSERTEMPLATE_23,
    LABELPRINTTEMPLATE_5,
    LABELPRINTTEMPLATE_6,
    LPUSERTEMPLATE_31,
    LPUSERTEMPLATE_32,
    LPUSERTEMPLATE_33,
}PRINTTEMPLATE;

typedef enum
{
    THREE_SPACES = 0,
    TEN_SPACES,
    FIFTEEN_SPACES,
    DATE,
    DISPLAYED_WEIGHT,
    END_OF_TEMPLATE,
    GROSS_WEIGHT,
    ID,
    NET_WEIGHT,
    NEW_LINE,
    SCALE_NAME,
    STRING_ONE,
    STRING_TWO,
    STRING_THREE,
    STRING_FOUR,
    STRING_FIVE,
    STRING_SIX,
    STRING_SEVEN,
    STRING_EIGHT,
    STRING_NINE,
    STRING_TEN,
    TARE_WEIGHT,
    TIME,
    TRANSACTION_NUMBER,
    AVERAGE_WEIGHT,
    NUMBER_OF_ANIMALS,
    AVG_PER_ANIMAL,
    OVERUNDER_COUNTER,
    OVERUNDER_TARGETDESCRIPTION,
    OVERUNDER_TARGETID,
    OVERUNDER_TARGETWEIGHT,
    OVERUNDER_TARGETTOLERENCE,
    OVERUNDER_TOTAL,
    OVERUNDER_ZONE,
    APW,
    PIECE_COUNT,
    RECORD_ID,
    RECORD_DESCRIPTION,
    PEAK_CYCLES,
    PEAK_AVG_WEIGHT,
    PEAK_MAX_WEIGHT,
    PEAK_MIN_WEIGHT,
    PEAK_WEIGHT,    
    EXID1,
    EXID2,
    EXID3,
    EXID4,
}TEMPLATEFIELD;

typedef enum
{
    PRINTSOURCE_COM0 = 0,
    PRINTSOURCE_COM1,
    PRINTSOURCE_COM2,
    PRINTSOURCE_ETHERNET,
    PRINTSOURCE_KEYBOARD,
    PRINTSOURCE_DIO
}DEMANDPRINTSOURCE;

typedef enum
{
    ICON_HIDDEN,
    ICON_SHOW
}ICONSTATUS;

typedef enum
{
    TWELVE_MINUTE = 0,
    TWELVE_MINUTE_SECOND,
    TWENTYFOUR_MINUTE,
    TWENTYFOUR_MINUTE_SECOND,
    TIMEFORMAT_NOTCARE
}TIMEFORMAT;

typedef enum
{
    DD_MM_YY = 0,
    DD_MMM_YYYY,
    MM_DD_YY,
    MMM_DD_YYYY,
    YY_MM_DD,
    YYYY_MMM_DD,
    YYYY_MM_DD,
    DATEFORMAT_NOTCARE
}DATEFORMAT;

typedef enum
{
    SEPARATOR_SLASH = 0,
    SEPARATOR_DASH,
    SEPARATOR_DOT,
    SEPARATOR_SPACE,
    SEPARATOR_NONE,
    DATESEPARATOR_NOTCARE
}DATESEPARATOR;

typedef enum
{
    TOTALIZATION_DISABLE = 0, 
    TOTALIZATION_DISPLAYEDWEIGHT,
    TOTALIZATION_GROSSWEIGHT
}TOTALIZATIONMODE;

typedef enum
{
    PACKAGE_NONE, 
    PACKAGE_ANIMALWEIGHING, 
    PACKAGE_CHECKWEIGHING, 
    PACKAGE_COUNTING, 
    PACKAGE_PEAKWEIGH,
    PACKAGE_SIMPLEWEIGHING,
}PACKAGEMODE; 

typedef enum
{
    TAREDISPLAY_DISABLE = 0, 
    TAREDISPLAY_ACTIVE,
    TAREDISPLAY_ALWAYS
}TAREDISPLAYMODE;

typedef enum
{
    POS_TRUE = 0,
    NEG_TRUE
}INPUT_POLARUTY; 

typedef enum
{
   INPUT_ASSIGNMENT_NONE = 0,
   INPUT_ASSIGNMENT_BLANK_DISPLAY,
   INPUT_ASSIGNMENT_CLEAR_TARE,
   INPUT_ASSIGNMENT_PRINT,
   INPUT_ASSIGNMENT_SICS_S,
   INPUT_ASSIGNMENT_SICS_SI,
   INPUT_ASSIGNMENT_SICS_SIR,
   INPUT_ASSIGNMENT_TARE,
   INPUT_ASSIGNMENT_UNIT_SWITCH,
   INPUT_ASSIGNMENT_ZERO,
   INPUT_ASSIGNMENT_START,
   INPUT_ASSIGNMENT_START_PEAK_WEIGH,
}INPUT_ASSIGNMENT;

typedef enum
{
    OUTPUT_ASSIGNMENT_NONE = 0,
    OUTPUT_ASSIGNMENT_CENTER_OF_ZERO,
    OUTPUT_ASSIGNMENT_MOTION,
    OUTPUT_ASSIGNMENT_NET,
    OUTPUT_ASSIGNMENT_OVER_CAPACITY,
    OUTPUT_ASSIGNMENT_UNDER_ZERO,
    OUTPUT_ASSIGNMENT_ANIMAL_CYCLE_COMPLETE,
    OUTPUT_ASSIGNMENT_ANIMAL_WORKING,
    OUTPUT_ASSIGNMENT_OK_ZONE,
    OUTPUT_ASSIGNMENT_OVER_ZONE,
    OUTPUT_ASSIGNMENT_UNDER_ZONE,
    OUTPUT_ASSIGNMENT_PEAK_RUNNING,
    OUTPUT_ASSIGNMENT_PEAK_CYCLE_COMPLETE,
    OUTPUT_ASSIGNMENT_COUNTING_EQUTARGET,
    OUTPUT_ASSIGNMENT_COUNTING_GRTTARGET,
    OUTPUT_ASSIGNMENT_COUNTING_LESTARGET,
}OUTPUT_ASSIGNMENT;
#endif
